USE [master]
GO

/****** Object:  Database [FLASH_SENSITIVE]    Script Date: 9/9/2022 2:00:34 AM ******/
CREATE DATABASE [FLASH_SENSITIVE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FLASH_SENSITIVE', FILENAME = N'D:\DATABASES\MSSQL\DATA\FLASH_SENSITIVE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FLASH_SENSITIVE_log', FILENAME = N'D:\DATABASES\MSSQL\DATA\FLASH_SENSITIVE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FLASH_SENSITIVE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FLASH_SENSITIVE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET ARITHABORT OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET RECOVERY FULL 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET  MULTI_USER 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FLASH_SENSITIVE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FLASH_SENSITIVE] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FLASH_SENSITIVE] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FLASH_SENSITIVE] SET  READ_WRITE 
GO



USE [FLASH_SENSITIVE]
GO
/****** Object:  Table [dbo].[SENSITIVE_LIST]    Script Date: 9/9/2022 2:02:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SENSITIVE_LIST](
	[ROW_ID] [bigint] NOT NULL,
	[SENSITIVE_WORD] [varchar](50) NOT NULL,
	[DATE_CREATED] [datetime] NULL,
	[DATE_MODIFIED] [datetime] NULL,
 CONSTRAINT [PK_SENSITIVE_LIST] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SENSITIVE_MESSAGES]    Script Date: 9/9/2022 2:02:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SENSITIVE_MESSAGES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MESSAGE_SENSITIVE] [varchar](max) NULL,
	[MESSAGE_MASKED] [varchar](max) NULL,
 CONSTRAINT [PK_SENSITIVE_MESSAGES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SENSITIVE_LIST] ADD  CONSTRAINT [DF_SQL_SENTITIVE_LIST_DATE_CREATED]  DEFAULT (getdate()) FOR [DATE_CREATED]
GO
ALTER TABLE [dbo].[SENSITIVE_LIST] ADD  CONSTRAINT [DF_SQL_SENTITIVE_LIST_DATE_MODIFIED]  DEFAULT (getdate()) FOR [DATE_MODIFIED]
GO
/****** Object:  StoredProcedure [dbo].[GET_MASKED_MESSAGE]    Script Date: 9/9/2022 2:02:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GET_MASKED_MESSAGE]
@MASK_SENSITIVE VARCHAR(max)
AS

--***TESTING***
--DECLARE @MASK_SENSITIVE VARCHAR(2000) --PARAM
--SET @MASK_SENSITIVE = ' ACTION ADD ALL ALLOCATE ALTER ANY APPLICATION ARE AREA ASC ASSERTION ATOMIC AUTHORIZATION AVG BEGIN BY CALL CASCADE CASCADED CATALOG CHECK CLOSE COLUMN COMMIT COMPRESS CONNECT CONNECTION CONSTRAINT CONSTRAINTS CONTINUE CONVERT CORRESPONDING CREATE CROSS CURRENT CURRENT_PATH CURRENT_SCHEMA CURRENT_SCHEMAID CURRENT_USER CURRENT_USERID CURSOR DATA DEALLOCATE DECLARE DEFAULT DEFERRABLE DEFERRED DELETE DESC DESCRIBE DESCRIPTOR DETERMINISTIC DIAGNOSTICS DIRECTORY DISCONNECT DISTINCT DO DOMAIN DOUBLEATTRIBUTE DROP EACH EXCEPT EXCEPTION EXEC EXECUTE EXTERNAL FETCH FLOAT FOREIGN FOUND FULL FUNCTION GET GLOBAL GO GOTO GRANT GROUP HANDLER HAVING IDENTITY IMMEDIATE INDEX INDEXED INDICATOR INITIALLY INNER INOUT INPUT INSENSITIVE INSERT INTERSECT INTO ISOLATION JOIN KEY LANGUAGE LAST LEAVE LEVEL LOCAL LONGATTRIBUTE LOOP MODIFIES MODULE NAMES NATIONAL NATURAL NEXT NULLIF ON ONLY OPEN OPTION ORDER OUT OUTER OUTPUT OVERLAPS OWNER PARTIAL PATH PRECISION PREPARE PRESERVE PRIMARY PRIOR PRIVILEGES PROCEDURE PUBLIC READ READS REFERENCES RELATIVE REPEAT RESIGNAL RESTRICT RETURN RETURNS REVOKE ROLLBACK ROUTINE ROW ROWS SCHEMA SCROLL SECTION SELECT SEQ SEQUENCE SESSION SESSION_USER SESSION_USERID SET SIGNAL SOME SPACE SPECIFIC SQL SQLCODE SQLERROR SQLEXCEPTION SQLSTATE SQLWARNING STATEMENT STRINGATTRIBUTE SUM SYSACC SYSHGH SYSLNK SYSNIX SYSTBLDEF SYSTBLDSC SYSTBT SYSTBTATT SYSTBTDEF SYSUSR SYSTEM_USER SYSVIW SYSVIWCOL TABLE TABLETYPE TEMPORARY TRANSACTION TRANSLATE TRANSLATION TRIGGER UNDO UNION UNIQUE UNTIL UPDATE USAGE USER USING VALUE VALUES VIEW WHERE WHILE WITH WORK WRITE ALLSCHEMAS ALLTABLES ALLVIEWS ALLVIEWTEXTS ALLCOLUMNS ALLINDEXES ALLINDEXCOLS ALLUSERS ALLTBTS TABLEPRIVILEGES TBTPRIVILEGES MYSCHEMAS MYTABLES MYTBTS MYVIEWS SCHEMAVIEWS DUAL SCHEMAPRIVILEGES SCHEMATABLES STATISTICS USRTBL STRINGTABLE LONGTABLE DOUBLETABLE SELECT * FROM'
--EXEC GET_MASKED_MESSAGE @MASK_SENSITIVE


DECLARE @MASK_WORD VARCHAR(50)
DECLARE @MASK_INDX INT
DECLARE @MASK_LENGTH INT

--(1) CREATE PROCESSING CURSOR
DECLARE CURSOR_MASK CURSOR 
FOR
SELECT SENSITIVE_WORD
FROM [dbo].[SENSITIVE_LIST]


OPEN CURSOR_MASK

FETCH NEXT FROM CURSOR_MASK 
INTO @MASK_WORD

--(2) PROCESS CURSOR MASK
WHILE @@FETCH_STATUS = 0  
BEGIN 
	
	SELECT 
	@MASK_INDX = CHARINDEX(@MASK_WORD,@MASK_SENSITIVE),
	@MASK_LENGTH = LEN(@MASK_WORD)
	
	IF (@MASK_INDX > 0)
	BEGIN
		SET @MASK_SENSITIVE = STUFF(@MASK_SENSITIVE, @MASK_INDX, @MASK_LENGTH,REPLICATE('*', @MASK_LENGTH))
	END

	FETCH NEXT FROM CURSOR_MASK 
	INTO @MASK_WORD
	
END

CLOSE CURSOR_MASK 

DEALLOCATE CURSOR_MASK 

--(3) RETURN RESULT
SELECT @MASK_SENSITIVE AS MASKED_SENSITIVE

GO
