// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Flash.Test.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Flash.Test.Data
{
    public partial class FlashContext
    {
        private IFlashContextProcedures _procedures;

        public virtual IFlashContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new FlashContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IFlashContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GET_MASKED_MESSAGEResult>().HasNoKey().ToView(null);
        }
    }

    public partial class FlashContextProcedures : IFlashContextProcedures
    {
        private readonly FlashContext _context;

        public FlashContextProcedures(FlashContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GET_MASKED_MESSAGEResult>> GET_MASKED_MESSAGEAsync(string MASK_SENSITIVE, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MASK_SENSITIVE",
                    Size = 2000,
                    Value = MASK_SENSITIVE ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GET_MASKED_MESSAGEResult>("EXEC @returnValue = [dbo].[GET_MASKED_MESSAGE] @MASK_SENSITIVE", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
