// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Flash.Test.Models;

namespace Flash.Test.Data
{
    public partial class FlashContext : DbContext
    {
        public FlashContext()
        {
        }

        public FlashContext(DbContextOptions<FlashContext> options)
            : base(options)
        {
        }

        public virtual DbSet<SensitiveList> SensitiveLists { get; set; }
        public virtual DbSet<SensitiveMessage> SensitiveMessages { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SensitiveList>(entity =>
            {
                entity.ToTable("SENSITIVE_LIST");

                entity.Property(e => e.RowId)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("ROW_ID");

                entity.Property(e => e.SensitiveWord)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("SENSITIVE_WORD");
            });

            modelBuilder.Entity<SensitiveMessage>(entity =>
            {
                entity.ToTable("SENSITIVE_MESSAGES");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.MessageMasked)
                    .IsUnicode(false)
                    .HasColumnName("MESSAGE_MASKED");

                entity.Property(e => e.MessageSensitive)
                    .IsUnicode(false)
                    .HasColumnName("MESSAGE_SENSITIVE");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}