// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Flash.Test.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Flash.Test.Data
{
    public partial interface IFlashContextProcedures
    {
        Task<List<GET_MASKED_MESSAGEResult>> GET_MASKED_MESSAGEAsync(string MASK_SENSITIVE, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
