// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using MessagePack;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;


namespace Flash.Test.Models
{
    public partial class GET_MASKED_MESSAGEResult
    {
        public string MASKED_SENSITIVE { get; set; }
   
    }
}
